// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uehfrahynnflrwmxnooc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlaGZyYWh5bm5mbHJ3bXhub29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjAzOTMsImV4cCI6MjA2MzUzNjM5M30.HDSaVaXlKr5Sn7QnPKzmGkbjQFXyXX3rPNcIRllwwuw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);